project:
  type: website

website:
  title: "tablero-prueba"
  sidebar:
    contents: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Acerca de
      - href: tablero.qmd
        text: Tablero

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

