project:
  type: website

website:
  title: "Tablero demo"
  favicon: images/logo.png
  page-navigation: true
  site-url: https://cballejo.github.io/tablero-prueba
  repo-url: https://github.com/cballejo/tablero-prueba
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Home
      - href: tablero.qmd
        text: Tablero

format:
  html:
    theme: [pulse, custom.scss]
    highlight-style: atom-one-dark
    toc: false
    grid:
      sidebar-width: 150px



